"""Phase N.2.3 — backend-only (FastAPI + Postgres + alembic) preset render."""

from __future__ import annotations

from gapt_server.domains.scaffolds.context import RenderContext
from gapt_server.domains.scaffolds.presets._shared import (
    PYTHON_GITIGNORE,
    mit_license,
)
from gapt_server.domains.scaffolds.registry import (
    ScaffoldOption,
    ScaffoldPreset,
    register,
)

_README = """\
# {project_name}

Backend starter generated by GAPT — FastAPI + asyncpg + alembic + Postgres.

## Quick start

```bash
git clone https://github.com/{github_owner}/{repo_name}.git
cd {repo_name}
docker compose up -d --build
docker compose exec backend alembic upgrade head
```

* API: http://localhost:{primary_port}/health
* Database name: `{db_name}` (user `postgres`, password `postgres`, host `postgres`)

## Layout

```
app/
  main.py    FastAPI app + lifespan
  db.py      asyncpg pool
alembic/     migration skeleton
docker-compose.yml
```

## Add a migration

```bash
docker compose exec backend alembic revision -m "describe me" --autogenerate
docker compose exec backend alembic upgrade head
```
"""

_MAIN_PY = """\
from contextlib import asynccontextmanager

import asyncpg
from fastapi import FastAPI

from app.db import init_pool, close_pool, get_pool


@asynccontextmanager
async def _lifespan(app: FastAPI):
    await init_pool()
    yield
    await close_pool()


app = FastAPI(title="{project_name}", lifespan=_lifespan)


@app.get("/health")
async def health() -> dict[str, str | int]:
    pool: asyncpg.Pool = get_pool()
    async with pool.acquire() as conn:
        val = await conn.fetchval("SELECT 1")
    return {{"status": "ok", "db": int(val) if val else 0}}
"""

_DB_PY = """\
\"\"\"asyncpg pool lifecycle.\"\"\"

from __future__ import annotations

import os

import asyncpg

_pool: asyncpg.Pool | None = None


def _dsn() -> str:
    return os.environ.get(
        "DATABASE_URL",
        "postgres://postgres:postgres@postgres:5432/{db_name}",
    )


async def init_pool() -> None:
    global _pool
    _pool = await asyncpg.create_pool(_dsn(), min_size=1, max_size=5)


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None


def get_pool() -> asyncpg.Pool:
    if _pool is None:
        raise RuntimeError("DB pool not initialised; lifespan didn't run.")
    return _pool
"""

_REQUIREMENTS = """\
fastapi==0.115.0
uvicorn[standard]==0.32.0
asyncpg==0.30.0
alembic==1.13.3
"""

_DOCKERFILE = """\
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY alembic ./alembic
COPY alembic.ini ./alembic.ini

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_ALEMBIC_INI = """\
[alembic]
script_location = alembic
sqlalchemy.url = postgres://postgres:postgres@postgres:5432/{db_name}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""

_ALEMBIC_ENV = """\
from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config
target_metadata = None


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
"""

_COMPOSE = """\
services:
  backend:
    build: .
    ports:
      - "{primary_port}:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/{db_name}
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {db_name}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
"""


def _render(ctx: RenderContext) -> dict[str, bytes]:
    primary_port = int(ctx.options.get("primary_port", 8000))
    db_name = str(ctx.options.get("db_name", "app"))
    return {
        "README.md": _README.format(
            project_name=ctx.project_name,
            github_owner=ctx.github_owner,
            repo_name=ctx.repo_name,
            primary_port=primary_port,
            db_name=db_name,
        ).encode("utf-8"),
        ".gitignore": PYTHON_GITIGNORE.encode("utf-8"),
        "LICENSE": mit_license(ctx.github_owner),
        "app/__init__.py": b"",
        "app/main.py": _MAIN_PY.format(project_name=ctx.project_name).encode("utf-8"),
        "app/db.py": _DB_PY.format(db_name=db_name).encode("utf-8"),
        "requirements.txt": _REQUIREMENTS.encode("utf-8"),
        "Dockerfile": _DOCKERFILE.encode("utf-8"),
        "alembic.ini": _ALEMBIC_INI.format(db_name=db_name).encode("utf-8"),
        "alembic/env.py": _ALEMBIC_ENV.encode("utf-8"),
        "alembic/versions/.gitkeep": b"",
        "docker-compose.yml": _COMPOSE.format(
            primary_port=primary_port, db_name=db_name
        ).encode("utf-8"),
    }


PRESET = ScaffoldPreset(
    id="backend_fastapi",
    display_name="Backend (FastAPI + Postgres)",
    description="Python FastAPI + asyncpg + alembic + Postgres. 백엔드 서비스 출발점.",
    stack=("FastAPI", "asyncpg", "alembic", "Postgres", "Docker Compose"),
    icon="server",
    deploy_target_kind="local",
    deploy_target_defaults={
        "compose_path": "docker-compose.yml",
        "primary_service": "backend",
        "primary_port": 8000,
        "preview_mode": "path",
        "strip_prefix": True,
        "build": True,
    },
    option_schema=(
        ScaffoldOption(
            id="primary_port",
            label="API 포트",
            type="integer",
            default=8000,
            description="backend 서비스의 외부 포트.",
            min_value=1,
            max_value=65535,
        ),
        ScaffoldOption(
            id="db_name",
            label="데이터베이스 이름",
            type="string",
            default="app",
            description="Postgres database 이름 (alembic + asyncpg 가 이걸로 연결).",
        ),
    ),
    render=_render,
)

register(PRESET)
