"""Phase N.2.3 — frontend SPA (Next.js standalone) preset render."""

from __future__ import annotations

from gapt_server.domains.scaffolds.context import RenderContext
from gapt_server.domains.scaffolds.presets._shared import (
    NODE_GITIGNORE,
    mit_license,
)
from gapt_server.domains.scaffolds.registry import (
    ScaffoldOption,
    ScaffoldPreset,
    register,
)


_README = """\
# {project_name}

Next.js 15 starter generated by GAPT.

## Quick start

```bash
git clone https://github.com/{github_owner}/{repo_name}.git
cd {repo_name}
docker compose up -d --build
```

* App: http://localhost:{primary_port}

Local dev (no Docker):

```bash
cd {repo_name}
npm install
npm run dev
```
"""

_PAGE_TSX_TAILWIND = """\
export default function Home() {{
  return (
    <main className="min-h-screen flex flex-col items-center justify-center gap-3 p-8">
      <h1 className="text-3xl font-semibold">{project_name}</h1>
      <p className="text-gray-500">
        Next.js 15 + App Router + Tailwind, scaffolded by GAPT.
      </p>
    </main>
  );
}}
"""

_PAGE_TSX_PLAIN = """\
export default function Home() {{
  return (
    <main style={{{{
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "0.75rem",
      padding: "2rem",
      fontFamily: "system-ui",
    }}}}>
      <h1 style={{{{ fontSize: "2rem", fontWeight: 600 }}}}>{project_name}</h1>
      <p style={{{{ color: "#666" }}}}>Next.js 15 + App Router, scaffolded by GAPT.</p>
    </main>
  );
}}
"""

_LAYOUT_TSX_TAILWIND = """\
import "./globals.css";

export const metadata = {{ title: "{project_name}" }};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="ko">
      <body>{{children}}</body>
    </html>
  );
}}
"""

_LAYOUT_TSX_PLAIN = """\
export const metadata = {{ title: "{project_name}" }};

export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <html lang="ko">
      <body style={{{{ margin: 0 }}}}>{{children}}</body>
    </html>
  );
}}
"""

_GLOBALS_CSS_TAILWIND = """\
@tailwind base;
@tailwind components;
@tailwind utilities;
"""

_PACKAGE_JSON_TAILWIND = """\
{{
  "name": "{slug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  }},
  "dependencies": {{
    "next": "15.0.3",
    "react": "19.0.0",
    "react-dom": "19.0.0"
  }},
  "devDependencies": {{
    "typescript": "5.6.3",
    "@types/node": "22.9.0",
    "@types/react": "19.0.0",
    "@types/react-dom": "19.0.0",
    "tailwindcss": "3.4.14",
    "postcss": "8.4.49",
    "autoprefixer": "10.4.20"
  }}
}}
"""

_PACKAGE_JSON_PLAIN = """\
{{
  "name": "{slug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  }},
  "dependencies": {{
    "next": "15.0.3",
    "react": "19.0.0",
    "react-dom": "19.0.0"
  }},
  "devDependencies": {{
    "typescript": "5.6.3",
    "@types/node": "22.9.0",
    "@types/react": "19.0.0",
    "@types/react-dom": "19.0.0"
  }}
}}
"""

_TAILWIND_CONFIG = """\
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
"""

_POSTCSS_CONFIG = """\
export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
"""

_NEXT_CONFIG = """\
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: "standalone",
};
export default nextConfig;
"""

_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

_DOCKERFILE = """\
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install --no-package-lock

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
"""

_COMPOSE = """\
services:
  frontend:
    build: .
    ports:
      - "{primary_port}:3000"
    restart: unless-stopped
"""


def _render(ctx: RenderContext) -> dict[str, bytes]:
    primary_port = int(ctx.options.get("primary_port", 3000))
    with_tailwind = bool(ctx.options.get("with_tailwind", True))

    files: dict[str, bytes] = {
        "README.md": _README.format(
            project_name=ctx.project_name,
            github_owner=ctx.github_owner,
            repo_name=ctx.repo_name,
            primary_port=primary_port,
        ).encode("utf-8"),
        ".gitignore": NODE_GITIGNORE.encode("utf-8"),
        "LICENSE": mit_license(ctx.github_owner),
        "next.config.mjs": _NEXT_CONFIG.encode("utf-8"),
        "tsconfig.json": _TSCONFIG.encode("utf-8"),
        "Dockerfile": _DOCKERFILE.encode("utf-8"),
        "docker-compose.yml": _COMPOSE.format(primary_port=primary_port).encode("utf-8"),
    }
    if with_tailwind:
        files["app/page.tsx"] = _PAGE_TSX_TAILWIND.format(project_name=ctx.project_name).encode("utf-8")
        files["app/layout.tsx"] = _LAYOUT_TSX_TAILWIND.format(project_name=ctx.project_name).encode("utf-8")
        files["app/globals.css"] = _GLOBALS_CSS_TAILWIND.encode("utf-8")
        files["package.json"] = _PACKAGE_JSON_TAILWIND.format(slug=ctx.slug).encode("utf-8")
        files["tailwind.config.ts"] = _TAILWIND_CONFIG.encode("utf-8")
        files["postcss.config.mjs"] = _POSTCSS_CONFIG.encode("utf-8")
    else:
        files["app/page.tsx"] = _PAGE_TSX_PLAIN.format(project_name=ctx.project_name).encode("utf-8")
        files["app/layout.tsx"] = _LAYOUT_TSX_PLAIN.format(project_name=ctx.project_name).encode("utf-8")
        files["package.json"] = _PACKAGE_JSON_PLAIN.format(slug=ctx.slug).encode("utf-8")
    return files


PRESET = ScaffoldPreset(
    id="frontend_nextjs",
    display_name="Frontend (Next.js)",
    description="Next.js 15 standalone — 랜딩, 포트폴리오, SPA.",
    stack=("Next.js 15", "App Router", "Tailwind", "Docker Compose"),
    icon="monitor",
    deploy_target_kind="local",
    deploy_target_defaults={
        "compose_path": "docker-compose.yml",
        "primary_service": "frontend",
        "primary_port": 3000,
        "preview_mode": "path",
        "strip_prefix": False,
        "upstream_scheme": "",
        "build": True,
    },
    option_schema=(
        ScaffoldOption(
            id="primary_port",
            label="Next.js 포트",
            type="integer",
            default=3000,
            description="frontend 서비스의 외부 포트.",
            min_value=1,
            max_value=65535,
        ),
        ScaffoldOption(
            id="with_tailwind",
            label="Tailwind CSS 포함",
            type="boolean",
            default=True,
            description="끄면 글로벌 CSS reset 만 포함.",
        ),
    ),
    render=_render,
)

register(PRESET)
