"""Phase N.2.3 — fullstack (FastAPI + Next.js + nginx) preset render.

Lays down a working 3-service stack:

  backend  — FastAPI on :8000, mounted at /api inside nginx
  frontend — Next.js 15 (App Router) on :3000, mounted at / inside nginx
  nginx    — single external port; reverse-proxies /api → backend, / → frontend

When the operator selects ``database=postgres``, a 4th service is added
with a tiny ``app/db.py`` that gives the FastAPI app an asyncpg pool.
The alembic skeleton (`alembic/`, `alembic.ini`) ships in either mode
so adding migrations later doesn't require an editor.
"""

from __future__ import annotations

from gapt_server.domains.scaffolds.context import RenderContext
from gapt_server.domains.scaffolds.presets._shared import (
    combined_gitignore,
    mit_license,
    NODE_GITIGNORE,
    PYTHON_GITIGNORE,
)
from gapt_server.domains.scaffolds.registry import (
    ScaffoldOption,
    ScaffoldPreset,
    register,
)

_README = """\
# {project_name}

Fullstack starter generated by GAPT — FastAPI backend + Next.js 15 frontend
behind nginx, all wired into one docker-compose.

## Quick start

```bash
git clone https://github.com/{github_owner}/{repo_name}.git
cd {repo_name}
docker compose up -d --build
```

* App:      http://localhost:{primary_port}
* API:      http://localhost:{primary_port}/api/health
* Backend:  http://localhost:8000/health  (direct, dev only)
* Frontend: http://localhost:3000         (direct, dev only)

## Layout

```
backend/    FastAPI + uvicorn
frontend/   Next.js 15, App Router
nginx/      reverse proxy: /api/* → backend, /* → frontend
docker-compose.yml
```

## Database

{database_section}
"""

_DATABASE_NONE = "Not configured. Re-scaffold with `database=postgres` or add your own."

_DATABASE_POSTGRES = """\
Postgres is wired in. FastAPI gets an asyncpg pool via `backend/app/db.py`.
Alembic skeleton lives in `backend/alembic/` — add migrations with:

```bash
docker compose exec backend alembic revision -m "describe me" --autogenerate
docker compose exec backend alembic upgrade head
```
"""

# ──────────────────────────────────────────────────── backend ──

_BACKEND_MAIN_NO_DB = """\
from fastapi import FastAPI

app = FastAPI(title="{project_name}")


@app.get("/health")
async def health() -> dict[str, str]:
    return {{"status": "ok"}}
"""

_BACKEND_MAIN_WITH_DB = """\
from contextlib import asynccontextmanager

import asyncpg
from fastapi import FastAPI

from app.db import init_pool, close_pool, get_pool


@asynccontextmanager
async def _lifespan(app: FastAPI):
    await init_pool()
    yield
    await close_pool()


app = FastAPI(title="{project_name}", lifespan=_lifespan)


@app.get("/health")
async def health() -> dict[str, str]:
    pool: asyncpg.Pool = get_pool()
    async with pool.acquire() as conn:
        val = await conn.fetchval("SELECT 1")
    return {{"status": "ok", "db": int(val) if val else 0}}
"""

_BACKEND_DB_PY = """\
\"\"\"asyncpg pool lifecycle. Imported by app.main's lifespan.\"\"\"

from __future__ import annotations

import os

import asyncpg

_pool: asyncpg.Pool | None = None


def _dsn() -> str:
    return os.environ.get(
        "DATABASE_URL",
        "postgres://postgres:postgres@postgres:5432/{db_name}",
    )


async def init_pool() -> None:
    global _pool
    _pool = await asyncpg.create_pool(_dsn(), min_size=1, max_size=5)


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None


def get_pool() -> asyncpg.Pool:
    if _pool is None:
        raise RuntimeError("DB pool not initialised; lifespan didn't run.")
    return _pool
"""

_BACKEND_REQS_NO_DB = """\
fastapi==0.115.0
uvicorn[standard]==0.32.0
"""

_BACKEND_REQS_WITH_DB = """\
fastapi==0.115.0
uvicorn[standard]==0.32.0
asyncpg==0.30.0
alembic==1.13.3
"""

_BACKEND_DOCKERFILE = """\
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

# Minimal alembic skeleton (so `alembic revision` works post-clone).

_ALEMBIC_INI = """\
[alembic]
script_location = alembic
sqlalchemy.url = postgres://postgres:postgres@postgres:5432/{db_name}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""

_ALEMBIC_ENV = """\
from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config
target_metadata = None


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {{}}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
"""

# ─────────────────────────────────────────────────── frontend ──

_FRONTEND_PAGE = """\
export default function Home() {{
  return (
    <main style={{{{ padding: "2rem", fontFamily: "system-ui" }}}}>
      <h1 style={{{{ fontSize: "2rem", fontWeight: 600 }}}}>{project_name}</h1>
      <p style={{{{ color: "#666", marginTop: "0.5rem" }}}}>
        Fullstack starter — backend at <code>/api</code>, frontend here at <code>/</code>.
      </p>
      <p style={{{{ marginTop: "1.5rem" }}}}>
        Health check:{{" "}}
        <a href="/api/health" style={{{{ color: "#0a66c2" }}}}>
          GET /api/health
        </a>
      </p>
    </main>
  );
}}
"""

_FRONTEND_LAYOUT = """\
export const metadata = {{
  title: "{project_name}",
}};

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <html lang="ko">
      <body style={{{{ margin: 0 }}}}>{{children}}</body>
    </html>
  );
}}
"""

_FRONTEND_PACKAGE_JSON = """\
{{
  "name": "{slug}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  }},
  "dependencies": {{
    "next": "15.1.6",
    "react": "19.0.0",
    "react-dom": "19.0.0"
  }},
  "devDependencies": {{
    "typescript": "5.6.3",
    "@types/node": "22.9.0",
    "@types/react": "19.0.0",
    "@types/react-dom": "19.0.0"
  }}
}}
"""

_FRONTEND_NEXT_CONFIG = """\
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: "standalone",
};
export default nextConfig;
"""

_FRONTEND_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

_FRONTEND_DOCKERFILE = """\
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install --no-package-lock

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
# CRITICAL: Next.js standalone's server.js binds to `localhost` by
# default. Inside a container that means it only listens on 127.0.0.1
# — nginx (next service in this compose) can't reach it, and the
# preview URL returns 502. `HOSTNAME=0.0.0.0` forces a bind on all
# interfaces so nginx + the published port both work.
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
"""

# ────────────────────────────────────────────────────── nginx ──

_NGINX_CONF = """\
events {}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
"""

_NGINX_DOCKERFILE = """\
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/nginx.conf
"""

# ───────────────────────────────────────────────── compose ──

_COMPOSE_NO_DB = """\
services:
  backend:
    build: ./backend
    expose:
      - "8000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    expose:
      - "3000"
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "{primary_port}:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
"""

_COMPOSE_WITH_DB = """\
services:
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/{db_name}
    depends_on:
      - postgres
    restart: unless-stopped
  frontend:
    build: ./frontend
    expose:
      - "3000"
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "{primary_port}:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {db_name}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
"""


def _render(ctx: RenderContext) -> dict[str, bytes]:
    primary_port = int(ctx.options.get("primary_port", 80))
    database = str(ctx.options.get("database", "none"))
    db_name = "app"  # baked default; backend preset exposes db_name as an option.

    files: dict[str, bytes] = {
        "README.md": _README.format(
            project_name=ctx.project_name,
            github_owner=ctx.github_owner,
            repo_name=ctx.repo_name,
            primary_port=primary_port,
            database_section=_DATABASE_POSTGRES if database == "postgres" else _DATABASE_NONE,
        ).encode("utf-8"),
        ".gitignore": combined_gitignore(PYTHON_GITIGNORE, NODE_GITIGNORE),
        "LICENSE": mit_license(ctx.github_owner),
        # ── backend
        "backend/app/__init__.py": b"",
        "backend/Dockerfile": _BACKEND_DOCKERFILE.encode("utf-8"),
        # ── frontend
        "frontend/app/page.tsx": _FRONTEND_PAGE.format(project_name=ctx.project_name).encode("utf-8"),
        "frontend/app/layout.tsx": _FRONTEND_LAYOUT.format(project_name=ctx.project_name).encode("utf-8"),
        "frontend/package.json": _FRONTEND_PACKAGE_JSON.format(slug=ctx.slug).encode("utf-8"),
        "frontend/next.config.mjs": _FRONTEND_NEXT_CONFIG.encode("utf-8"),
        "frontend/tsconfig.json": _FRONTEND_TSCONFIG.encode("utf-8"),
        "frontend/Dockerfile": _FRONTEND_DOCKERFILE.encode("utf-8"),
        # ── nginx
        "nginx/nginx.conf": _NGINX_CONF.encode("utf-8"),
        "nginx/Dockerfile": _NGINX_DOCKERFILE.encode("utf-8"),
    }
    if database == "postgres":
        files["backend/app/main.py"] = _BACKEND_MAIN_WITH_DB.format(
            project_name=ctx.project_name
        ).encode("utf-8")
        files["backend/app/db.py"] = _BACKEND_DB_PY.format(db_name=db_name).encode("utf-8")
        files["backend/requirements.txt"] = _BACKEND_REQS_WITH_DB.encode("utf-8")
        files["backend/alembic.ini"] = _ALEMBIC_INI.format(db_name=db_name).encode("utf-8")
        files["backend/alembic/env.py"] = _ALEMBIC_ENV.encode("utf-8")
        files["backend/alembic/versions/.gitkeep"] = b""
        files["docker-compose.yml"] = _COMPOSE_WITH_DB.format(
            primary_port=primary_port, db_name=db_name
        ).encode("utf-8")
    else:
        files["backend/app/main.py"] = _BACKEND_MAIN_NO_DB.format(
            project_name=ctx.project_name
        ).encode("utf-8")
        files["backend/requirements.txt"] = _BACKEND_REQS_NO_DB.encode("utf-8")
        files["docker-compose.yml"] = _COMPOSE_NO_DB.format(
            primary_port=primary_port
        ).encode("utf-8")
    return files


PRESET = ScaffoldPreset(
    id="fullstack_fastapi_nextjs",
    display_name="Full-stack (FastAPI + Next.js)",
    description="백엔드 / 프론트엔드 / 리버스 프록시가 한 번에 — SaaS 풀스택 출발점.",
    stack=("FastAPI", "Next.js 15", "nginx", "Docker Compose"),
    icon="layers",
    deploy_target_kind="local",
    deploy_target_defaults={
        "compose_path": "docker-compose.yml",
        "primary_service": "nginx",
        "primary_port": 80,
        "preview_mode": "subdomain",
        "build": True,
    },
    option_schema=(
        ScaffoldOption(
            id="primary_port",
            label="외부 포트",
            type="integer",
            default=80,
            description="nginx 가 노출할 포트 (preview 라우팅 대상).",
            min_value=1,
            max_value=65535,
        ),
        ScaffoldOption(
            id="database",
            label="데이터베이스",
            type="enum",
            default="none",
            description="postgres 선택 시 4번째 서비스 + alembic 추가.",
            choices=("none", "postgres"),
        ),
    ),
    render=_render,
)

register(PRESET)
