"""Phase N.2.3 — static site (Vite + nginx) preset render.

Multi-stage Dockerfile: ``node`` stage builds the dist tree via
``npm run build``, ``nginx:alpine`` stage serves it. One container,
one external port."""

from __future__ import annotations

from gapt_server.domains.scaffolds.context import RenderContext
from gapt_server.domains.scaffolds.presets._shared import (
    NODE_GITIGNORE,
    mit_license,
)
from gapt_server.domains.scaffolds.registry import (
    ScaffoldOption,
    ScaffoldPreset,
    register,
)


_README = """\
# {project_name}

Static site starter generated by GAPT — Vite + TypeScript built to a
plain dist tree, served by nginx.

## Quick start

```bash
git clone https://github.com/{github_owner}/{repo_name}.git
cd {repo_name}
docker compose up -d --build
```

Site: http://localhost:{primary_port}

Local dev (no Docker):

```bash
npm install
npm run dev
```
"""

_INDEX_HTML = """\
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{project_name}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
"""

_MAIN_TS = """\
import "./style.css";

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `
  <main>
    <h1>{project_name}</h1>
    <p>Vite + TypeScript, scaffolded by GAPT.</p>
  </main>
`;
"""

_STYLE_CSS = """\
:root {
  font-family: system-ui, sans-serif;
  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;
}

body {
  margin: 0;
  min-height: 100vh;
  display: flex;
  place-items: center;
  justify-content: center;
}

main {
  text-align: center;
  padding: 2rem;
}

h1 {
  font-size: 2.5rem;
  font-weight: 600;
  margin: 0 0 0.5rem 0;
}

p {
  color: #888;
  margin: 0;
}
"""

_PACKAGE_JSON = """\
{{
  "name": "{slug}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  }},
  "devDependencies": {{
    "typescript": "5.6.3",
    "vite": "5.4.10"
  }}
}}
"""

_VITE_CONFIG = """\
import { defineConfig } from "vite";

export default defineConfig({
  build: { outDir: "dist" },
});
"""

_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "noEmit": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "include": ["src"]
}
"""

_NGINX_CONF = """\
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
"""

_DOCKERFILE = """\
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --no-package-lock
COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runner
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
"""

_COMPOSE = """\
services:
  static:
    build: .
    ports:
      - "{primary_port}:80"
    restart: unless-stopped
"""


def _render(ctx: RenderContext) -> dict[str, bytes]:
    primary_port = int(ctx.options.get("primary_port", 80))
    return {
        "README.md": _README.format(
            project_name=ctx.project_name,
            github_owner=ctx.github_owner,
            repo_name=ctx.repo_name,
            primary_port=primary_port,
        ).encode("utf-8"),
        ".gitignore": NODE_GITIGNORE.encode("utf-8"),
        "LICENSE": mit_license(ctx.github_owner),
        "index.html": _INDEX_HTML.format(project_name=ctx.project_name).encode("utf-8"),
        "src/main.ts": _MAIN_TS.format(project_name=ctx.project_name).encode("utf-8"),
        "src/style.css": _STYLE_CSS.encode("utf-8"),
        "package.json": _PACKAGE_JSON.format(slug=ctx.slug).encode("utf-8"),
        "vite.config.ts": _VITE_CONFIG.encode("utf-8"),
        "tsconfig.json": _TSCONFIG.encode("utf-8"),
        "nginx/nginx.conf": _NGINX_CONF.encode("utf-8"),
        "Dockerfile": _DOCKERFILE.encode("utf-8"),
        "docker-compose.yml": _COMPOSE.format(primary_port=primary_port).encode("utf-8"),
    }


PRESET = ScaffoldPreset(
    id="static_vite",
    display_name="Static site (Vite + nginx)",
    description="Vite 빌드 + nginx 서빙 — 문서 / 정적 랜딩 / 포트폴리오.",
    stack=("Vite", "TypeScript", "nginx", "Docker Compose"),
    icon="file-text",
    deploy_target_kind="local",
    deploy_target_defaults={
        "compose_path": "docker-compose.yml",
        "primary_service": "static",
        "primary_port": 80,
        "preview_mode": "path",
        "build": True,
    },
    option_schema=(
        ScaffoldOption(
            id="primary_port",
            label="nginx 포트",
            type="integer",
            default=80,
            description="static 서비스의 외부 포트.",
            min_value=1,
            max_value=65535,
        ),
    ),
    render=_render,
)

register(PRESET)
