"""initial schema (single-admin)

Revision ID: 0001
Revises: 
Create Date: 2026-05-26 00:27:01.051823
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_agent_prefs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('cost_budget_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=True),
    sa.Column('permission_mode', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_agent_prefs'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'agent_session', 'system', name='audit_actor_type_enum'), nullable=False),
    sa.Column('actor_id', sa.String(length=26), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('outcome', sa.Enum('ok', 'error', 'denied', name='audit_outcome_enum'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('exec_code', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action_ts', 'audit_events', ['action', 'ts'], unique=False)
    op.create_index('ix_audit_events_ts', 'audit_events', ['ts'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('git_remote_url', sa.Text(), nullable=False),
    sa.Column('git_provider', sa.Enum('github', 'gitlab', 'gitea', 'generic', name='git_provider_enum'), nullable=False),
    sa.Column('git_auth_secret_ref', sa.Text(), nullable=True),
    sa.Column('default_compose_paths', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('compose_profile_dev', sa.String(length=80), nullable=True),
    sa.Column('compose_profile_prod', sa.String(length=80), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', name=op.f('uq_projects_slug'))
    )
    # sandboxes ↔ workspaces have a circular FK (each ON DELETE SET
    # NULL points at the other). Postgres requires both tables to
    # exist before the FK is created — so we create `sandboxes`
    # without the workspace_id FK first, then add it back after
    # `workspaces` is in place.
    op.create_table('sandboxes',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('workspace_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.Enum('creating', 'running', 'paused', 'stopped', 'failed', name='sandbox_status_enum'), server_default='creating', nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.Column('resource_limits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sandboxes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sandboxes'))
    )
    op.create_table('secrets',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('owner_scope', sa.Enum('system', 'project', 'environment', name='secret_owner_scope_enum'), nullable=False),
    sa.Column('owner_id', sa.String(length=26), nullable=False),
    sa.Column('key_name', sa.String(length=200), nullable=False),
    sa.Column('backend', sa.Enum('keyring', 'encrypted_sqlite', 'sops', 'infisical', name='secret_backend_enum'), nullable=False),
    sa.Column('backend_ref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('owner_scope', 'owner_id', 'key_name', name='uq_secrets_scope_owner_key')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('worktree_path', sa.Text(), nullable=False),
    sa.Column('sandbox_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.Enum('creating', 'running', 'paused', 'stopped', 'failed', 'archived', name='workspace_status_enum'), server_default='creating', nullable=False),
    sa.Column('port_assignments', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workspaces_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], name=op.f('fk_workspaces_sandbox_id_sandboxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index('ix_workspaces_project_status', 'workspaces', ['project_id', 'status'], unique=False)
    # Now that workspaces exists, close the cycle with sandboxes.
    op.create_foreign_key(
        'fk_sandboxes_workspace_id_workspaces',
        'sandboxes', 'workspaces',
        ['workspace_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('env_manifest_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale_idle', 'stale_compact', 'archived', name='agent_session_status_enum'), server_default='active', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_sessions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    op.create_index('ix_agent_sessions_project_status', 'agent_sessions', ['project_id', 'status'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('deploy_target_kind', sa.Enum('local', 'remote_ssh', 'webhook', 'k8s', name='deploy_target_kind_enum'), nullable=False),
    sa.Column('deploy_target_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('require_2fa', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('secret_refs', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('cost_multiplier', sa.Numeric(precision=8, scale=4), server_default='1', nullable=False),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_run', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_environments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('project_id', 'name', name='uq_environments_project_name')
    )
    op.create_table('deploy_runs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('environment_id', sa.String(length=26), nullable=False),
    sa.Column('version', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('bound_url', sa.Text(), nullable=True),
    sa.Column('exec_code', sa.String(length=80), nullable=True),
    sa.Column('log_tail', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('trigger_kind', sa.String(length=40), server_default='manual', nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_deploy_runs_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deploy_runs'))
    )
    op.create_index('ix_deploy_runs_environment_id', 'deploy_runs', ['environment_id'], unique=False)
    op.create_index('ix_deploy_runs_started_at', 'deploy_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deploy_runs_started_at', table_name='deploy_runs')
    op.drop_index('ix_deploy_runs_environment_id', table_name='deploy_runs')
    op.drop_table('deploy_runs')
    op.drop_table('environments')
    op.drop_index('ix_agent_sessions_project_status', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # Drop the cycle FK before dropping workspaces so the table drop
    # isn't blocked.
    op.drop_constraint('fk_sandboxes_workspace_id_workspaces', 'sandboxes', type_='foreignkey')
    op.drop_index('ix_workspaces_project_status', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('secrets')
    op.drop_table('sandboxes')
    op.drop_table('projects')
    op.drop_index('ix_audit_events_ts', table_name='audit_events')
    op.drop_index('ix_audit_events_action_ts', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('admin_agent_prefs')
    # `sa.Enum` only auto-drops the type on a column drop when the
    # type was created implicitly. We created them inline with
    # CREATE TYPE during upgrade, so we have to drop them explicitly
    # — otherwise `downgrade base` leaves the enum types behind and
    # the migration round-trip test asserts a non-empty set.
    sa.Enum(name='deploy_target_kind_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agent_session_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workspace_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sandbox_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='secret_backend_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='secret_owner_scope_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='git_provider_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_outcome_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_actor_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
