"""provider_migrations

Revision ID: fd2e71745ed6
Revises: 9d411d5f596a
Create Date: 2026-05-28 09:52:14.316798
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd2e71745ed6'
down_revision: str | Sequence[str] | None = '9d411d5f596a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_migrations',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('provider_kind', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_migrations'))
    )
    op.create_index('ix_provider_migrations_provider_kind_started_at', 'provider_migrations', ['provider_kind', 'started_at'], unique=False)
    op.create_index('ix_provider_migrations_started_at', 'provider_migrations', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_migrations_started_at', table_name='provider_migrations')
    op.drop_index('ix_provider_migrations_provider_kind_started_at', table_name='provider_migrations')
    op.drop_table('provider_migrations')
    # ### end Alembic commands ###
